### ISSUE TITLE
Not all tabs are exported

### ISSUE THREAD

**Issue by hmijail** [alct/export-tabs-urls#3] opened 2018-07-01 14:35 UTC
I have a lot of tabs (800-ish) open across multiple windows. The add-on's dialog only shows a fraction of them (66). Any idea why? 
(of those 800, about 40 are loaded, the rest are not; so it's not that those 66 are the loaded ones)

**Comment by alct** [comment] 2018-07-01 14:52
Hello @hmijail,

Thank you for your feedback.

> I have a lot of tabs (800-ish) open across multiple windows.
> The add-on's dialog only shows a fraction of them (66).
> Any idea why?

Not yet :)

Could you please provide me with some info about :

- your Operating System, Firefox version and the Export Tabs URLs version
- how many Firefox windows are open
- what are the protocols of the open tabs (https, http,...)

?

**Comment by hmijail** [comment] 2018-07-01 15:25
Yep, sorry. This is Firefox 62.0b4 (64-bit), on macOS 10.13.5, with Export Tabs URLs 0.1.10. 

There are 8 windows, and the tabs in Export Tabs URLs' dialog seem to come from all of them.

The protocols of the tabs in general and of those exported by ETU in particular are a mixture of https (the majority of them) and http.

**Comment by alct** [comment] 2018-07-05 16:02
I have started to investigate this issue. I can not reproduce it yet.

@hmijail Do you use any extension that could interfere with how tabs are processed?

| OS | Browser | Containers | Number of window |  Number of open tabs per window | Number of tabs exported by ETU |
|---|---|---|---|---|---|
| Windows | Firefox nightly | yes | 1 | 150 | 150 |
| Linux | Firefox nightly | yes | 1 | 150 | 150 |
| Linux | Firefox nightly | yes | 10 | 20 | 200 |
| MacOS 10.13.5  | Firefox 62.0b2 | yes | 2 | 859 + 20 | 879 |

**Comment by hmijail** [comment] 2018-07-07 14:42
I'm not sure what could count as "interfering with how tabs are processed", but I do have a number of add-ons dealing with tabs: TreeStyleTabs, AllTabsHelper, Multiple Tab Handler, OneTab, Open Links in Tabs, Tab Session Manager, Crappy Firetitle, Tab Unloader for TreeStyleTabs.

**Comment by alct** [comment] 2018-07-07 23:30
I have tried increasing the amount of window just in case it could be related but have still not managed to reproduce the issue. At this point it is very likely caused by another extension.

Could you please try the following procedure : backup your firefox profile, disable all addons but ETU and check whether it fixes the issue or not. Then, progressively re-enable the other extensions.

Here is how to do so:

### Backup your current profile

- in Firefox, in the address bar, go to `about:support`
- find the "Profile Directory" line and copy the path
- close Firefox
- in your terminal `cp -r /path/to/firefox/your.profile /path/to/firefox/your.profile.backup`
- make sure that the backup is an exact copy of your profile `diff -qr /path/to/firefox/your.profile /path/to/firefox/your.profile.backup` (if there is no output, you are good)

### Disable all addons but ETU

- launch Firefox
- in Firefox, in the address bar, go to `about:addons`, disable all addons but ETU
- restart Firefox

### Check whether it fixes the issues

- check whether ETU reports the right amount of tabs
- progressively re-enable the other addons and check whether it has any influence on ETU
- once you are done testing, close Firefox

### Restore your profile

- go to the directory containing your profile `/path/to/firefox/`
- move `your.profile` to trash (in a reversible way just in case something went wrong)
- rename `your.profile.backup` to `your.profile`
- restart Firefox

**Comment by E3V3A** [comment] 2018-08-25 20:57
@hmijail 
Yeah dude, if one plugin (extension) is already dealing with tabs, you don't want another to do the same.

**Comment by alct** [comment] 2018-11-10 13:59
Closing this issue given the lack of updates after 4 months.

**Closed as completed by alct** 2018-11-10 13:59 UTC
Labels: info needed
