### ISSUE TITLE
Every 15th TAB is overwritten by google.com

### ISSUE THREAD

**Issue by E3V3A** [alct/export-tabs-urls#5] opened 2018-08-25 21:22 UTC
This is weird as hell! 
Every 15th TAB that is exported, is replaced by a google.com URL, writing over what was there before. 
This is very bad!

PS. Running on Win + `60.1.0esr (64-bit)`

**Comment by alct** [comment] 2018-08-25 23:08
Hello,

Thank you for your feedback. That is really weird indeed.

Luckily enough, ETU is free software :wink: so you can inspect the [code](https://github.com/alct/export-tabs-urls/blob/master/popup/popup.js) and check for yourself that there isn't any reference to google or any obfuscated line that could do some nasty stuff like this.

This being said, I'm curious about about what could be causing such a behavior.

1. Is it precisely and consistently the 15th tab (do you mean 15, 30, 45,... or only the 15th)?
2. Is there anything special with this/these tab(s) whose URL is replaced with google's?
3. Do you have any other extension that could be interfering with how tabs are processed?

I couldn't reproduce the issue, so I'm pretty confident that another extension/something else is messing with the tabs.

4. Could you please follow these [instructions to help with the debugging](https://github.com/alct/export-tabs-urls/issues/3#issuecomment-403249687) (given that you are on windows, just manually copy/paste your profile directory at the _"Backup your current profile"_ step rather than using the commands provided)?

**Comment by E3V3A** [comment] 2018-09-04 09:07
FWIW
(Sorry, But I'm a bit too time constrained today, so lets see if I can do step 4 at a later time.)

Answers:

1. It's every 15th. `(15,30,45,..)`
2. Nothing special
3. TBH, I don't remember, I tried several extensions at the time. 
4. I will keep this in mind

**Comment by alct** [comment] 2018-11-10 14:01
Hello @E3V3A ,

Any update on this? Do you still use ETU? Has this problem occurred again?

**Comment by alct** [comment] 2019-01-18 05:10
Closing this issue given the lack of updates after 3 months.
(do not hesitate to comment with new info, I'll gladly re-open it)

**Closed as completed by alct** 2019-01-18 05:10 UTC
Labels: info needed

**Comment by E3V3A** [comment] 2019-01-23 08:35
Hi @alct 
Sorry for not being able to follow up on the debugging. I simply stopped using your extension as I found another that worked. 
Good Luck.

**Comment by E3V3A** [comment] 2019-01-23 10:47
I just tested your new updates! Works great! 
Thanks. :+1:
